use_frameworks!

target 'UIViewControllerRotation_Example' do
  pod 'UIViewControllerRotation', :path => '../'

  target 'UIViewControllerRotation_Tests' do
    inherit! :search_paths

    
  end
end
