use_frameworks!

target 'UIViewControllerRotation_Example' do
    pod 'UIViewControllerRotation', :path => '../'
  
end


target 'UIViewControllerRotation_Example_OC' do
    pod 'UIViewControllerRotation', :path => '../'
end
