platform :ios, '9.0'

install! 'cocoapods', :share_schemes_for_development_pods => false

use_frameworks!

target 'UIViewControllerRotation_Example' do
    pod 'UIViewControllerRotate', :path => '../'
end

